# Generated by Django 5.0.6 on 2024-05-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyincome',
            name='income_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
