# Generated by Django 5.0.6 on 2024-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor_app', '0002_monthlyincome_income_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyincome',
            name='deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
