# Generated by Django 5.0.6 on 2024-05-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tresor_app', '0003_alter_expenses_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyincome',
            name='deposit_date',
        ),
    ]
