# Generated by Django 5.0.6 on 2024-05-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tresor_app', '0004_remove_monthlyincome_deposit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='due_date',
        ),
    ]
